### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by amoreiras** [amoreiras/markdown-portfolio#2]
- [x] Additional markup is supported, including @mentions, #referencess, [links](url), **emphasis**, and <del>HTML tags</del>.
- [x] List syntax is required.
  - You can nest lists below, too!
- [x] This item is completed.
- [ ] This item is not complete.
